global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    
  # Add scrape config for your aggregator service if it exposes metrics
  - job_name: 'aggregator'
    static_configs:
      - targets: ['aggregator:9080']
